WITH CTE AS (
    SELECT
        *,
        LAG(VEHICLE_TYPES_AVAILABLE_ICONIC) OVER (PARTITION BY STATION_ID ORDER BY ID ASC) AS PREV_VEHICLE_ICONIC
    FROM
        STATION_STATUS
    WHERE
        STATION_ID = 7148
        AND ID >= 1890764
),
COUNTS AS (
    SELECT
        STATION_ID,
        LAST_REPORTED,
        VEHICLE_TYPES_AVAILABLE_ICONIC,
        PREV_VEHICLE_ICONIC,
        VEHICLE_TYPES_AVAILABLE_ICONIC - COALESCE(PREV_VEHICLE_ICONIC, VEHICLE_TYPES_AVAILABLE_ICONIC) AS DELTA,
        SUM(
            CASE WHEN VEHICLE_TYPES_AVAILABLE_ICONIC - COALESCE(PREV_VEHICLE_ICONIC, VEHICLE_TYPES_AVAILABLE_ICONIC) < 0 THEN
                VEHICLE_TYPES_AVAILABLE_ICONIC - GREATEST (0, COALESCE(PREV_VEHICLE_ICONIC, VEHICLE_TYPES_AVAILABLE_ICONIC))
            ELSE
                0
            END) OVER (PARTITION BY STATION_ID) AS COUNT_UNDOCKINGS,
        SUM(
            CASE WHEN VEHICLE_TYPES_AVAILABLE_ICONIC - COALESCE(PREV_VEHICLE_ICONIC, VEHICLE_TYPES_AVAILABLE_ICONIC) > 0 THEN
                VEHICLE_TYPES_AVAILABLE_ICONIC - GREATEST (0, COALESCE(PREV_VEHICLE_ICONIC, VEHICLE_TYPES_AVAILABLE_ICONIC))
            ELSE
                0
            END) OVER (PARTITION BY STATION_ID) AS COUNT_DOCKINGS
    FROM
        CTE
)
SELECT
    MAX(COUNT_DOCKINGS) AS DOCKING_COUNT,
    MAX(COUNT_UNDOCKINGS) AS UNDOCKING_COUNT
FROM
    COUNTS;

