WITH CTE AS (
    SELECT
        *,
        LAG(VEHICLE_TYPES_AVAILABLE_ICONIC) OVER (PARTITION BY STATION_ID ORDER BY ID ASC) AS PREV_ICONIC,
        LAG(VEHICLE_TYPES_AVAILABLE_EFIT) OVER (PARTITION BY STATION_ID ORDER BY ID ASC) AS PREV_EFIT,
        LAG(VEHICLE_TYPES_AVAILABLE_EFIT_G5) OVER (PARTITION BY STATION_ID ORDER BY ID ASC) AS PREV_EFIT_G5
    FROM
        STATION_STATUS
    WHERE
        last_reported >= '2023-10-11 00:00:00-04' AND
        last_reported <= '2023-10-12 00:00:00-04' AND
        station_id = 7015
),
COUNTS AS (
    SELECT
        STATION_ID,
        LAST_REPORTED,
        VEHICLE_TYPES_AVAILABLE_ICONIC as iconic,
        VEHICLE_TYPES_AVAILABLE_EFIT as efit,
        VEHICLE_TYPES_AVAILABLE_EFIT_G5 as efit_g5,
        PREV_ICONIC,
        PREV_EFIT,
        PREV_EFIT_G5,
        VEHICLE_TYPES_AVAILABLE_ICONIC - COALESCE(PREV_ICONIC, VEHICLE_TYPES_AVAILABLE_ICONIC) AS DELTA_ICONIC,
        VEHICLE_TYPES_AVAILABLE_EFIT - COALESCE(PREV_EFIT, VEHICLE_TYPES_AVAILABLE_EFIT) AS DELTA_EFIT,
        VEHICLE_TYPES_AVAILABLE_EFIT_G5 - COALESCE(PREV_EFIT_G5, VEHICLE_TYPES_AVAILABLE_EFIT_G5) AS DELTA_EFIT_G5,
        SUM(VEHICLE_TYPES_AVAILABLE_ICONIC - COALESCE(PREV_ICONIC, VEHICLE_TYPES_AVAILABLE_ICONIC)
        ) FILTER (WHERE VEHICLE_TYPES_AVAILABLE_ICONIC - COALESCE(PREV_ICONIC, VEHICLE_TYPES_AVAILABLE_ICONIC) > 0
        ) OVER (PARTITION BY STATION_ID) AS dockings_iconic,
        SUM(VEHICLE_TYPES_AVAILABLE_EFIT - COALESCE(PREV_EFIT, VEHICLE_TYPES_AVAILABLE_EFIT)
        ) FILTER (WHERE VEHICLE_TYPES_AVAILABLE_EFIT - COALESCE(PREV_EFIT, VEHICLE_TYPES_AVAILABLE_EFIT) > 0
        ) OVER (PARTITION BY STATION_ID) AS dockings_efit,
        SUM(VEHICLE_TYPES_AVAILABLE_EFIT_G5 - COALESCE(PREV_EFIT_G5, VEHICLE_TYPES_AVAILABLE_EFIT_G5)
        ) FILTER (WHERE VEHICLE_TYPES_AVAILABLE_EFIT_G5 - COALESCE(PREV_EFIT_G5, VEHICLE_TYPES_AVAILABLE_EFIT_G5) > 0
        ) OVER (PARTITION BY STATION_ID) AS dockings_efit_g5,
        SUM(VEHICLE_TYPES_AVAILABLE_ICONIC - COALESCE(PREV_ICONIC, VEHICLE_TYPES_AVAILABLE_ICONIC)
        ) FILTER (WHERE VEHICLE_TYPES_AVAILABLE_ICONIC - COALESCE(PREV_ICONIC, VEHICLE_TYPES_AVAILABLE_ICONIC) < 0
        ) OVER (PARTITION BY STATION_ID) AS undockings_iconic,
        SUM(VEHICLE_TYPES_AVAILABLE_EFIT - COALESCE(PREV_EFIT, VEHICLE_TYPES_AVAILABLE_EFIT)
        ) FILTER (WHERE VEHICLE_TYPES_AVAILABLE_EFIT - COALESCE(PREV_EFIT, VEHICLE_TYPES_AVAILABLE_EFIT) < 0
        ) OVER (PARTITION BY STATION_ID) AS undockings_efit,
        SUM(VEHICLE_TYPES_AVAILABLE_EFIT_G5 - COALESCE(PREV_EFIT_G5, VEHICLE_TYPES_AVAILABLE_EFIT_G5)
        ) FILTER (WHERE VEHICLE_TYPES_AVAILABLE_EFIT_G5 - COALESCE(PREV_EFIT_G5, VEHICLE_TYPES_AVAILABLE_EFIT_G5) < 0
        ) OVER (PARTITION BY STATION_ID) AS undockings_efit_g5
    FROM
        CTE
    WHERE
        VEHICLE_TYPES_AVAILABLE_ICONIC - COALESCE(PREV_ICONIC, VEHICLE_TYPES_AVAILABLE_ICONIC) != 0 OR
        VEHICLE_TYPES_AVAILABLE_EFIT - COALESCE(PREV_EFIT, VEHICLE_TYPES_AVAILABLE_EFIT) != 0 OR
        VEHICLE_TYPES_AVAILABLE_EFIT_G5 - COALESCE(PREV_EFIT_G5, VEHICLE_TYPES_AVAILABLE_EFIT_G5) != 0
)
SELECT
    station_id,
    last_reported,
    iconic,
    prev_iconic,
    delta_iconic,
    dockings_iconic,
    undockings_iconic,
    efit,
    prev_efit,
    delta_efit,
    dockings_efit,
    undockings_efit,
    efit_g5,
    prev_efit_g5,
    delta_efit_g5,
    dockings_efit_g5,
    undockings_efit_g5
FROM
    COUNTS;
