((nil . ((lsp-nix-nil-formatter . ("nixpkgs-fmt"))
         (lsp-haskell-plugin-stan-global-on . nil)
         (eglot-workspace-configuration . (:haskell (:formattingProvider "stylish-haskell")))
         (haskell-process-args-cabal-repl . ("--ghc-option=-ferror-spans"))
         (lsp-lens-enable . nil))))
